defmodule FinMan.Repo.Migrations.AddMetadataToTransfers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ledger_transfers) do
      add :description, :text
      add :category, :text
      add :date, :date, null: false, default: fragment("CURRENT_DATE")
    end
  end

  def down do
    alter table(:ledger_transfers) do
      remove :date
      remove :category
      remove :description
    end
  end
end
