defmodule FinMan.Repo.Migrations.CascadeDeletedTransfers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:ledger_balances, "ledger_balances_transfer_id_fkey")

    alter table(:ledger_balances) do
      modify :transfer_id,
             references(:ledger_transfers,
               column: :id,
               name: "ledger_balances_transfer_id_fkey",
               type: :binary,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:ledger_balances, "ledger_balances_transfer_id_fkey")

    alter table(:ledger_balances) do
      modify :transfer_id,
             references(:ledger_transfers,
               column: :id,
               name: "ledger_balances_transfer_id_fkey",
               type: :binary,
               prefix: "public"
             )
    end
  end
end
