defmodule FinMan.Repo.Migrations.RemoveCategoriesFromTransfers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ledger_transfers) do
      remove :category
    end
  end

  def down do
    alter table(:ledger_transfers) do
      add :category, :text
    end
  end
end
